In [15]:
a=int(input("enter the no:"))
b=int(input("enter the no:"))
add=a+b
add

enter the no: 45
enter the no: 56


101

install numpy


In [16]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [17]:
print(np.__version__)

1.26.4


In [18]:
print(np.__version__)

1.26.4


In [21]:
import numpy 
arr=np.array([1,2,3,4,4,5,6])
print(arr)

[1 2 3 4 4 5 6]


In [8]:
import numpy 
arr=numpy.array([1,2,3,4,4,5,6])
print(arr)
print(type(arr))


[1 2 3 4 4 5 6]
<class 'numpy.ndarray'>


In [3]:
#acess element in 2D array
import numpy as np
arr2=np.array([[1,2,3,4,5],[2,3,4,45,2]])
print(arr2)
print(arr2[1,-3])
print(np.max(arr2))

[[ 1  2  3  4  5]
 [ 2  3  4 45  2]]
4
45


In [28]:
import numpy as np
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access element array

In [32]:
import numpy as np
arr= np.array([1,2,3,4])
print(arr[0])
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr1[0,1])   #access element 2-D

1
2nd element on 1st row: 2


Numpy Array Slicing

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[-3:-1])       #slicing
print(arr[1:5:2])      #step vise[starting point,ending point,gap] 

print(arr.ndim)     #check daimention



[2 3 4 5]
[5 6]
[2 4]
int32
1


numpy datatype

In [13]:
arr=np.array([1,2,3,4,"4",5,6])
print(arr)
print(arr.dtype)     #datatype


['1' '2' '3' '4' '4' '5' '6']
<U11


numpy array shape

In [14]:
# 1D array
arr= np.array([2,4,5,7,8,9,3])
arr.shape

(7,)

In [18]:
#2D array
arr=np.array([[2,3,4,5,6,4],[1,2,3,4,5,6]])
arr.shape

(2, 6)

numpy reshape

In [21]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
new_arr=arr.reshape(10,1)
new_arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]])

numpy array iterating

In [22]:
#iterating for 1D
arr=np.array([1,2,3,4,5,6,7,8,9,0])
for i in arr:    #or for i in range (0,10);
    print(i)    #print(arr[i])

1
2
3
4
5
6
7
8
9
0


In [ ]:
#iterating for 2D


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
newarr= arr1+arr2
newarr

array([4, 6, 8])

In [7]:
#split
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
split_arr=np.array_split(arr,3)
split_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [8]:
#where
arr = np.array([3,4,5,6,7])
search = np.where(arr==5)
search

(array([2], dtype=int64),)

In [9]:
#sort
arr=([1,2,3,4,5,6,8,9])
print(np.sort(arr)[::-1])

[9 8 6 5 4 3 2 1]


In [4]:
import numpy as np
arr= np.array([5,10,15])
arr=arr*2
arr

array([10, 20, 30])

In [6]:
import pandas as pd
df=pd.DataFrame({'name':[1,2,3],'score':[4,5,6]})
print(df.iloc[1])

name     2
score    5
Name: 1, dtype: int64
